// TotalUsage.js
export const LOAD_USAGE = 'LOAD_USAGE';
export const USAGE_LOADING = 'USAGE_LOADING'
// SliderDateSelector.js
export const SLIDER_SELECTOR_LOADED = 'SLIDER_SELECTOR_LOADED';
export const SLIDER_SELECTOR_LOADING = 'SLIDER_SELECTOR_LOADING';
